### ISSUE TITLE
ADD Block POSENC 

### ISSUE THREAD

**Issue by AMMARAicha** [PandABlocks/PandABlocks-webcontrol#7]
Hello,
I'm a new member of the ISAC group and I need a POSENC block for my project. After compiling, I received this output: panda-fpga PandABox-posenc_block-3.0a2-168-gf67231e-dirty. Previously, I successfully obtained a similar block for ADC. My question is: why isn't this block (module) available after installing PandA? Additionally, if I install a new firmware, will the last installed firmware be removed?
Thank You

**Comment by coretl** [comment]
I need a bit more information to be able to help. Please can you post a screenshot of http://<panda-ip>/admin/packages/list, and the output of `echo *BLOCKS? | nc <panda-ip> 8888`?

**Comment by coretl** [comment]
Also, the `app.ini` file you used to make `PandABox-posenc_block-3.0a2-168-gf67231e-dirty`

**Comment by AMMARAicha** [comment]
ZPKG LIST : 

root@panda:/tmp# zpkg list
panda-fpga PandABox-posenc_block-3.0a2-168-gf67231e-dirty
panda-server 2.1
panda-webcontrol-no-subnet-validation 2.1
panda-webcontrol 2.1

for app.ini i just add module posenc 
[.]
description:
    Standard set of PandABox blocks with:
        - module posenc
         
target: PandABox
includes: common_soft_blocks.include.ini

[POSENC]
module: posenc
and i have this error [ammar@laboca-el8-1 ~]$ python3.8  /home/informatique/eca/ammar/acq427/bin/pandablocks control 172.16.3.44
Traceback (most recent call last):
  File "/home/informatique/eca/ammar/acq427/bin/pandablocks", line 8, in <module>
    sys.exit(cli())
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/pandablocks/cli.py", line 61, in control
    interactive_control(host, prompt, not no_readline)
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/pandablocks/_control.py", line 137, in interactive_control
    client.connect()
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/pandablocks/blocking.py", line 53, in connect
    self._ctrl_socket.connect(self._host, 8888)
  File "/home/informatique/eca/ammar/.local/lib/python3.8/site-packages/pandablocks/blocking.py", line 17, in connect
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by coretl** [comment]
You cannot mix `2.x` and `3.x` releases. Please use the 3.0 releases from https://github.com/PandABlocks/PandABlocks.github.io/releases, both the zpkgs and the rootfs, check it works, then rebuild your FPGA zpkg and load it and check it still works. If it doesn't then `cat /var/log/messages` to see the error

**Comment by AMMARAicha** [comment]
I have this problem when i install it
Starting zpkg: Starting panda-server: PandA firmware not installed

**Comment by AMMARAicha** [comment]
sorry but i have a another question can i use panda_webcontrol 3.0.zpkg and panda-server 3.0a2.zpkg with panda-fpga 3.0a2.zpkg

**Comment by coretl** [comment]
> I have this problem when i install it Starting zpkg: Starting panda-server: PandA firmware not installed

Please can you paste the whole terminal output in a code block when you get this

**Comment by coretl** [comment]
> sorry but i have a another question can i use panda_webcontrol 3.0.zpkg and panda-server 3.0a2.zpkg with panda-fpga 3.0a2.zpkg

Possibly, but it would be better to rebase your branch on top of PandABlocks-FPGA master branch

**Comment by AMMARAicha** [comment]
[FIRMWARE NOT INSTALLED.txt](https://github.com/PandABlocks/PandABlocks-webcontrol/files/13490662/FIRMWARE.NOT.INSTALLED.txt)
